[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-cli-alarm"
version = "1.0.0"
authors = [
  { name="Sai Surla" },
]
description = "A resilient, zero-dependency, drift-free Python CLI alarm clock"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Environment :: Console",
]

[project.scripts]
alarm = "src.alarm_clock.main:main"
pyalarm = "src.alarm_clock.main:main"
